<?php
/**
 * Created by PhpStorm.
 * User: Jason
 * Date: 11/11/2015
 * Time: 7:48 PM
 */
require('ui_utilities.inc');

function ui_show_items_retrieved($message, $items_retrieved_result)
{
    //----------------------------------------------------------
    // Start the html page
    ui_print_header("UPDATE EVENT");

    echo "<center><h3>Select the Event you wish to update.</h3></center>";
    // If the message is non-null and not an empty string print it
    // message contains the lastname and firstname




}